export const projects = [
  {
    title: "Crypto Dashboard",
    description: "",
    image: "/images/cryto-dashboard.png",
    tags: ["Vue", "JavaScript", "Vuetify", "Apexcharts", "Tailwind"],
    source: "https://github.com/deepakkumardewani/crypto-dashboard",
    visit: "https://crypto-dashboard-rosy.vercel.app/#/",
    id: 0,
  },
  {
    title: "Metaverse",
    description: "",
    image: "/images/metaverse.png",
    tags: ["React", "JavaScript", "NextJS"],
    source: "https://github.com/deepakkumardewani/react-metaverse",
    visit: "https://react-metaverse-two.vercel.app/",
    id: 1,
  },
  {
    title: "Codex - ChatGPT Clone",
    description: "",
    image: "/images/chatgpt.png",
    tags: ["NodeJS", "HTML", "CSS", "Express"],
    source: "https://github.com/deepakkumardewani/chatgpt-clone",
    visit: "https://chatgpt-clone-smoky.vercel.app/",
    id: 2,
  },
  {
    title: "Realtor - Modern Real State",
    description: "",
    image: "/images/realstate.png",
    tags: ["React", "NextJS", "Javascript"],
    source: "https://github.com/deepakkumardewani/modern-real-state",
    visit: "https://modern-real-state-kqoc.vercel.app/",
    id: 3,
  },
  {
    title: "ShareMe",
    description: "",
    image: "/images/shareme.png",
    tags: ["React", "NextJS", "Javascript", "Tailwind", "NodeJS"],
    source: "https://github.com/deepakkumardewani/react-shareme",
    visit: "https://react-shareme-ashen.vercel.app/",
    id: 3,
  },
  {
    title: "ModernGPT",
    description: "",
    image: "/images/moderngpt.png",
    tags: ["React", "Javascript"],
    source: "https://github.com/deepakkumardewani/modern_gpt",
    visit: "https://modern-gpt-three.vercel.app/",
    id: 3,
  },
  {
    title: "AI Image",
    description: "",
    image: "/images/aiimage.png",
    tags: ["React", "NextJS", "Javascript", "Tailwind", "NodeJS", "Cloudinary"],
    source: "https://github.com/deepakkumardewani/ai_image",
    visit: "https://ai-image-alpha.vercel.app/",
    id: 3,
  },
  {
    title: "Modern Bank",
    description: "",
    image: "/images/reactbank.png",
    tags: ["React", "Javascript", "Tailwind"],
    source: "https://github.com/deepakkumardewani/react_bank_app",
    visit: "https://react-bank-app-seven.vercel.app/",
    id: 3,
  },
  {
    title: "Blog App",
    description: "",
    image: "/images/blogapp.png",
    tags: ["React", "Javascript", "Tailwind", "GraphQL"],
    source: "https://github.com/deepakkumardewani/react-blog-app",
    visit: "https://react-blog-app-ruby.vercel.app/",
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: "Started my journey" },
  { year: 2018, text: "Worked as a freelance developer" },
  { year: 2019, text: "Founded JavaScript Mastery" },
  { year: 2020, text: "Shared my projects with the world" },
  { year: 2021, text: "Started my own platform" },
];
